### ISSUE TITLE
[Suggestion] NoCavesNoRavine for fabric

### ISSUE THREAD

**Issue by BoogieMonster1O1** [MatthiasMann/NoCavesNoRavines#1]
Fabric is a lightweight mod loader. Fabric is the future of modding because it helps to do almost everything the vanilla way and saves lots of time on loading mods and creating mods. Since it even supports snapshots, many mods like Tech Reborn, Replay Mod, Voxelmap, and Litematica have switched to fabric completely, and some mods like Worldedit, Lithium, and Immersive Railroading have started using fabric. Unlike forge, fabric doesn't have a ton of unnecessary events, and everything is handled by Mixins. No messy asm, and complete freedom.
I suggest making two sub-projects, one for fabric and one for forge.

**Comment by MatthiasMann** [comment]
I'm using Forge while playing Minecraft and as such won't port this mod to Fabric.

You are free to do that yourself if you like.
